language: node_js
node_js:
  - 0.10
  - 6
  - 8
  - 10
  - 12
  - 14
after_success:
  - if [ `node -p 'process.version.slice(0, 3)'` != "v8." ]; then exit; fi
  - npm install -g nyc coveralls
  - nyc -r text-lcov npm test | coveralls
